Charter for Bazel-IntelliJ plug-in SIG.
bazelbuild/community pull request #2
Opened 2022-07-08 20:42 UTC by raoarun

2022-07-08 20:45 UTC, raoarun commented
registered github account.

2022-07-08 20:49 UTC, raoarun commented
@sventiffe please review the SIG charter pull request.  i will add content to it shortly.  thanks.

2022-07-11 17:09 UTC, raoarun commented
@sventiffe please review the SIG charter pull request.  thank you.

2022-07-11 17:20 UTC, raoarun commented
please add @jastice to the list of reviewers, @sventiffe ... thank you!

2022-07-12 01:34 UTC, hicksjoseph approved these changes

2022-07-12 09:25 UTC, sventiffe requested changes
Charter LGTM, only two nits about link targets

2022-07-12 09:25 UTC, sventiffe commented on sigs/bazel-intellij/CHARTER.md
> +This SIG is open to anybody who uses, develops, or has an interest in sharing or absorbing knowledge on Bazel and the IntelliJ IDE plug-in. Please join bazel-intellij@googlegroups.com and share with
I'd add a link to the actual group for simplicity (ie makes it easier to join and to view conversations)
[bazel-intellij@googlegroups.com](https://groups.google.com/g/bazel-intellij)

2022-07-12 09:25 UTC, sventiffe commented on sigs/bazel-intellij/CHARTER.md
> +* bazel-intellij@googlegroups.com
[bazel-intellij@googlegroups.com](https://groups.google.com/g/bazel-intellij)

2022-07-12 09:28 UTC, sventiffe commented
> please add @jastice to the list of reviewers, @sventiffe ... thank you!

I've added Justin as collaborator to the repo, which is required before being able to review a PR. Access control is something we need to fine tune (@aiuto for awareness -- would it be an alternative to add an org level team to this repo so that every known collaborator could create a PR and be added as a reviewer?)

2022-07-12 17:21 UTC, raoarun commented on sigs/bazel-intellij/CHARTER.md
> +This SIG is open to anybody who uses, develops, or has an interest in sharing or absorbing knowledge on Bazel and the IntelliJ IDE plug-in. Please join bazel-intellij@googlegroups.com and share with
thanks @sventiffe

2022-07-12 17:22 UTC, raoarun commented on sigs/bazel-intellij/CHARTER.md
> +* bazel-intellij@googlegroups.com
thanks @sventiffe

2022-07-12 17:47 UTC, raoarun commented
@sventiffe i made the changes you requested.  ptal and lmk.  thanks!

2022-07-13 12:40 UTC, sventiffe approved these changes

2022-07-16 04:30 UTC, sventiffe approved these changes

2022-07-16 19:31 UTC, raoarun commented
@sventiffe how do we merge this into main?

2022-07-18 05:54 UTC, merged